'use strict';
/**
 * reminderJob.js — the structured, hallucination-safe reminder heartbeat.
 *
 * Flow:
 *   1. Build a grounded candidate list from the DB (contextBuilder).
 *   2. If empty → exit silently (no LLM call, no send).
 *   3. Otherwise ask an LLM which candidates deserve a reminder RIGHT NOW.
 *      The LLM is given exactly ONE tool — send_reminder(source_type,
 *      source_id, reason) — and is forbidden from emitting free text. It may
 *      only reference ids from the candidate list.
 *   4. Every tool call is re-checked against the candidate list (defence in
 *      depth) and then routed through guardedSend, which validates against the
 *      DB again before anything leaves. Blocked attempts are logged.
 *
 * The LLM never writes message text. It only selects. Text comes from templates.
 */

const https = require('https');

const { getUpcomingEvents } = require('./contextBuilder');
const { guardedSend } = require('../delivery/guardedSend');
const { logBlocked } = require('../validation/sourceValidator');

const API_KEY = process.env.ANTHROPIC_API_KEY;
const MODEL = process.env.REMINDER_JOB_MODEL || 'claude-haiku-4-5';

const SEND_REMINDER_TOOL = {
  name: 'send_reminder',
  description: 'Send a single grounded reminder for one event from the candidate list. You may ONLY call this with a source_type and source_id that appear verbatim in the candidate list provided by the user. Never invent ids.',
  input_schema: {
    type: 'object',
    properties: {
      source_type: { type: 'string', enum: ['notice_event', 'calendar_intents'], description: 'The source table of the event' },
      source_id: { type: 'integer', description: 'The exact id of the event from the candidate list' },
      reason: { type: 'string', description: 'Short reason this event warrants a reminder now' },
    },
    required: ['source_type', 'source_id', 'reason'],
  },
};

const SYSTEM_PROMPT = [
  'You are the reminder selector for a family assistant bot.',
  'You are shown a list of REAL upcoming events, each with a source_type and a numeric source_id.',
  'Your ONLY capability is to call the send_reminder tool. You MUST NOT write any free-text message, explanation, or reminder wording — message text is generated by a template, not by you.',
  'Rules:',
  '1. Only call send_reminder with a source_type + source_id pair that appears EXACTLY in the candidate list.',
  '2. Never invent, guess, combine, or modify ids. Never blend two events into one.',
  '3. Only remind about events that genuinely warrant a heads-up now (imminent or important).',
  '4. If nothing warrants a reminder, do nothing — return no tool calls.',
  '5. Never output prose. Only tool calls.',
].join('\n');

/** Low-level Anthropic call with tool use. Returns parsed response object. */
function callAnthropicWithTools(system, userText) {
  if (!API_KEY) throw new Error('[reminderJob] ANTHROPIC_API_KEY not set');
  const body = JSON.stringify({
    model: MODEL,
    max_tokens: 1024,
    system,
    tools: [SEND_REMINDER_TOOL],
    messages: [{ role: 'user', content: userText }],
  });

  return new Promise((resolve, reject) => {
    const req = https.request({
      hostname: 'api.anthropic.com',
      path: '/v1/messages',
      method: 'POST',
      timeout: 20000,
      headers: {
        'x-api-key': API_KEY,
        'anthropic-version': '2023-06-01',
        'content-type': 'application/json',
        'content-length': Buffer.byteLength(body),
      },
    }, res => {
      let data = '';
      res.on('data', c => data += c);
      res.on('end', () => {
        try {
          const r = JSON.parse(data);
          if (r.error) return reject(new Error(`[reminderJob] ${r.error.message}`));
          resolve(r);
        } catch (e) {
          reject(new Error(`[reminderJob] Parse error: ${data.slice(0, 200)}`));
        }
      });
    });
    req.on('timeout', () => { req.destroy(); reject(new Error('[reminderJob] LLM request timed out')); });
    req.on('error', reject);
    req.write(body);
    req.end();
  });
}

function buildCandidateText(candidates) {
  const lines = candidates.map(c =>
    `- source_type=${c.source_type} source_id=${c.source_id} | "${c.title}" | ${c.date}${c.time ? ' ' + c.time : ''}`
  );
  return `Current time: ${new Date().toISOString()}\n\nCandidate events (these are the ONLY valid ids):\n${lines.join('\n')}\n\nCall send_reminder for each event that should be reminded about now. If none, do nothing.`;
}

/**
 * Run one pass of the reminder job.
 * @param {object} [opts]
 * @param {number} [opts.hoursAhead=6]
 * @returns {Promise<{candidates:number, sent:number, blocked:number}>}
 */
async function runReminderJob(opts = {}) {
  const hoursAhead = opts.hoursAhead ?? 6;
  const { notice_events, calendar_events } = getUpcomingEvents(hoursAhead);
  const candidates = [...notice_events, ...calendar_events];

  if (candidates.length === 0) {
    return { candidates: 0, sent: 0, blocked: 0 };
  }

  // Candidate allow-set for the defence-in-depth check.
  const allow = new Set(candidates.map(c => `${c.source_type}:${c.source_id}`));

  let response;
  try {
    response = await callAnthropicWithTools(SYSTEM_PROMPT, buildCandidateText(candidates));
  } catch (err) {
    console.error('[reminderJob]', err.message);
    return { candidates: candidates.length, sent: 0, blocked: 0, error: err.message };
  }

  const blocks = Array.isArray(response.content) ? response.content : [];
  const toolCalls = blocks.filter(b => b.type === 'tool_use' && b.name === 'send_reminder');

  // Guard against the LLM emitting free text despite instructions — log it.
  const strayText = blocks.filter(b => b.type === 'text' && b.text && b.text.trim()).map(b => b.text.trim());
  if (strayText.length) {
    logBlocked('llm_free_text', { text: strayText.join('\n') }, 'LLM emitted free text — ignored');
    console.warn('[reminderJob] Ignored stray LLM text (guard):', strayText.join(' ').slice(0, 120));
  }

  let sent = 0, blocked = 0;
  for (const call of toolCalls) {
    const { source_type, source_id, reason } = call.input || {};
    const key = `${source_type}:${source_id}`;

    // Extra check: must be in the candidate list we actually gave the model.
    if (!allow.has(key)) {
      logBlocked('send_reminder', { source_type, source_id, reason }, `not in candidate list (${key})`);
      console.warn(`[reminderJob] BLOCKED hallucinated candidate ${key}`);
      blocked++;
      continue;
    }

    const result = await guardedSend(source_type, source_id, { reason });
    if (result.sent) sent++;
    else blocked++;
  }

  console.log(`[reminderJob] candidates=${candidates.length} sent=${sent} blocked=${blocked}`);
  return { candidates: candidates.length, sent, blocked };
}

module.exports = { runReminderJob };
