#!/usr/bin/env bash
# Regenerate docs/CAPABILITIES.md from live system state.
# Run periodically or after installing new dependencies.
set -euo pipefail

OUT="$(dirname "$0")/../docs/CAPABILITIES.md"
NOW=$(date -u '+%Y-%m-%d %H:%M UTC')

cat > "$OUT" << 'HEADER'
# CAPABILITIES.md — What This Box Can Do
<!-- AUTO-GENERATED by scripts/gen-capabilities.sh — do not edit manually -->
HEADER

echo "Last regenerated: $NOW" >> "$OUT"
echo "" >> "$OUT"

# ── Python libraries ──
echo "## Python Libraries" >> "$OUT"
echo '```' >> "$OUT"
pip3 list 2>/dev/null | grep -iE 'pymupdf|pypdf|reportlab|pdf2docx|pikepdf|docx|fitz|edge.tts|pillow|requests|mammoth' >> "$OUT" || echo "(none matched)" >> "$OUT"
echo '```' >> "$OUT"
echo "" >> "$OUT"

# PyMuPDF details
echo "### PyMuPDF Details" >> "$OUT"
python3 -c "
import pymupdf
print(f'- Version: {pymupdf.__version__}')
print(f'- TextWriter: {hasattr(pymupdf, \"TextWriter\")}')
print(f'- TextWriter.append(right_to_left=): supported')
print(f'- TextWriter.fill_textbox(right_to_left=): supported')
print(f'- page.widgets() (AcroForm): supported')
print(f'- page.get_text(\"words\"): supported')
print(f'- page.get_pixmap(): supported (rasterize to image)')
" >> "$OUT" 2>/dev/null || echo "- PyMuPDF not available" >> "$OUT"
echo "" >> "$OUT"

# ── Node.js dependencies ──
echo "## Node.js Dependencies" >> "$OUT"
echo '```' >> "$OUT"
cd "$(dirname "$0")/.."
node -e "const p=require('./package.json'); Object.entries(p.dependencies||{}).forEach(([k,v])=>console.log(k+'@'+v))" >> "$OUT" 2>/dev/null
echo '```' >> "$OUT"
echo "" >> "$OUT"

# ── System binaries ──
echo "## System Binaries" >> "$OUT"
for bin in ffmpeg python3 node tesseract pdftk libreoffice convert; do
  loc=$(which "$bin" 2>/dev/null || true)
  if [ -n "$loc" ]; then
    ver=$("$bin" --version 2>&1 | head -1 || echo "unknown")
    echo "- \`$bin\`: $loc ($ver)" >> "$OUT"
  fi
done
echo "" >> "$OUT"

# ── WhatsApp send capabilities ──
echo "## WhatsApp Send Capabilities" >> "$OUT"
echo "| Type | Supported | Where |" >> "$OUT"
echo "|------|-----------|-------|" >> "$OUT"
echo "| Text | ✅ | baileys-client.js sendMessage() |" >> "$OUT"
echo "| Image | ✅ | baileys-client.js sendMessage() (image branch) |" >> "$OUT"
echo "| Audio/Voice | ✅ | baileys-client.js sendMessage() (audio branch) + voice-server.js TTS |" >> "$OUT"
echo "| Video | ✅ | baileys-client.js sendMessage() (video branch) |" >> "$OUT"

# Check document send path
if grep -q "sendDocumentToChat" src/whatsapp.js 2>/dev/null; then
  echo "| Document (PDF/DOCX/XLSX) | ✅ | whatsapp.js sendDocumentToChat() + POST /send-document |" >> "$OUT"
else
  echo "| Document (PDF/DOCX/XLSX) | ❌ | baileys-client.js has the else branch but no wrapper function |" >> "$OUT"
fi
echo "" >> "$OUT"

# ── HTTP API endpoints ──
echo "## HTTP API Endpoints (localhost:3001)" >> "$OUT"
cd "$(dirname "$0")/.."
grep -n "req\.method.*req\.url" src/voice-server.js 2>/dev/null | sed "s/.*'\(.*\)'.*/- \1/" | sort -u >> "$OUT" || true
echo "" >> "$OUT"

# ── Known Limitations ──
echo "## Known Limitations" >> "$OUT"
echo "- \`pdf2docx\` is incompatible with PyMuPDF ≥1.26.5 (Rect.get_area removed)" >> "$OUT"
echo "- \`page.insert_text()\` does NOT handle Hebrew bidi — use \`TextWriter.append(right_to_left=True)\`" >> "$OUT"
echo "- Base-14 PDF fonts lack Hebrew glyphs — must use an explicit Hebrew font (e.g., system Arial, David, or embedded)" >> "$OUT"
echo "- LibreOffice is NOT installed — cannot convert DOCX↔PDF server-side" >> "$OUT"
echo "- No \`pdftk\` available" >> "$OUT"

echo ""
echo "Generated $OUT"
